import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { UserContextProvider } from "@/app/context/userContext"; // Import UserContextProvider for managing user data

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Away Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-custom-background`}>
        <SessionProvider>
          <UserContextProvider> {/* Provide user context throughout the application */}
            {children} {/* Render the child components */}
          </UserContextProvider>
      </SessionProvider>
    </body>
    </html >
  );
}
